### PR TITLE
Got another one for ya!

### PR DESCRIPTION
**Pull request by colinta**
This time, if the `<select>` is blank, it shows prints `"null"` instead of `""`.

Easy fix:  assign `html` to a variable, check to see if it's `null`, and set to `""` if it is.

### CODE REVIEW

**Comment by adamcoulombe** [comment]
hey, did you try this? it doesnt work for me... you dont set the html var before trying to use it.

Also if you pass something as options.empty, the width doesn't register properly the way it is.

I updated my branch with a working fix for the null issue, have a look.

**Comment by colinta** [comment]
Aw, crap - I copied and pasted the code from my editor using github's "edit in place", and messed it up.

I'll rebase from yours, then.

**Comment by colinta** [comment]
k, updated.  I don't understand what you're saying about using options.  This is just a way of specifying the "empty" value.

How about this:

``` javascript
if(!html){ html=(options && options.empty ? options.empty : '&nbsp;'); }
```

**Comment by adamcoulombe** [comment]
Yep, which would enable you to pass in a string to appear as the empty value like so: 

$('#myselect').customSelect({ empty:'Nothing to see here!' });

But the size of .customStyleSelectBox span won't have a properly adjusted width because the string wasn't there in the original select box. (unless that select box had a CSS width already applied)

**Comment by colinta** [comment]
Ah, I see what you're saying. That makes sense - if you want an "empty" message, it should just be included in the `<select>` to begin with. 

Close it up! I'm changing my code to just include an "empty" `<option>` element.

**Pull request closed without merging**
