### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by bmatzner**
Hello Adam,

thanks for your nice plugin. I did some refactoring I thought may be helpful.
I have a few other modifications (e.g. added a component.json that points to my repository) that may not be suitable for a pull request, but nonetheless you may want to look at them.
Some other comments: it seems for jquery plugins a file naming like jquery-customselect.js or jquery.customselect.js seems to establish as a standard, you may want to think about renaming the file.
In addition, as most jQuery plugins are dual-licensed under MIT/GPL that may make it more flexible for people to use it.

Cheers,
Bernd

### CODE REVIEW

**Comment by adamcoulombe** [comment]
@bmatzner I like your changes. I'm just not sure about the new extra span. Is there any particular use case?

**Comment by bmatzner** [comment]
The need for the extra span was reusing a sprite icon for the "down" triangle from jQuery UI, in which that particular triangle is part of a larger image. In order to correctly display and position, some element like a span is necessary, and I thought this may apply not only to this particular use case, and I don't see it does much harm or adds too much weight to the plugin.
Another way of doing it could be to provide a "template" option, which is optional and would overwrite the nested spans much like you allow for custom class names.

**Comment by adamcoulombe** [comment]
Though it doesn't add a lot of weight, I'm just concerned it may add confusion to those who want to quickly figure out how it works, what to style... To be honest I don't even like the innerSpan being there but it is kind of necessary... I can see some people making use of the extra span but personally I think it just seems a little overkill... 

I do like the template idea if it could be done without adding a ton of extra code. What do you think?

I can merge your other changes for now if you want.

**Comment by bmatzner** [comment]
Hey, I can see your point, and that would be fine if we can think about the template insertion.

If you merge changes, I'll take it from there and suggest a slim solution, I think it can be done with very little extra code.

If I have some other changes in the future, I'll make them more atomic, this was just the result of making this plugin work for the project I want to use it in.

One thing I think should be done some time is create a "changed" event rather than call the "changed" function twice, even though it's now in the local scope its name could be too generic ...

**Comment by adamcoulombe** [comment]
@bmatzner thanks, I've made a lot of the changes you suggested including renaming the files etc. Your probably going to want to merge upstream or whatever before working on it any further. Maybe you can keep another branch for your version and have a different one to just push smaller updates like you said...

**Pull request merged**
