### PR TITLE
Update jquery.customSelect.js

### PR DESCRIPTION
**Pull request by stano**
should have disabled support

### CODE REVIEW

**Comment by stano** [comment]
Ok, your project :-)

**Comment by adamcoulombe** [comment]
Thanx. "disabled" is just too generic for use in a plugin I feel and the rest of the classes we use are all customSelect****

**Comment by adamcoulombe** [comment]
Hey would you be able to make the change to your commit, and I can merge it. Thanks!

**Comment by stano** [comment]
I don't know if my commit was emailed to you automatically, so I wrote this note :-)

**Comment by baohouse** [comment]
What about disabled options? One case study is where a fresh form has a select element whose first option is used as a label for the select field. e.g.

<code>&lt;select&gt;
&lt;option disabled&gt;Select gender&lt;/option&gt;
&lt;option value="M" &gt;Male&lt;/option&gt;
&lt;option value="F" &gt;Female&lt;/option&gt;
</code>

We apply "disabled" attribute on that option so that it does two things. First, it prevents the user from selecting that option when the dropdown shows. Second, it is used as a CSS selector to have a custom text color to simulate the &lt;input&gt; placeholder attribute.

Ideally the span element should have that disabled class if a disabled option is selected.

**Pull request merged**
