### PR TITLE
Correct position/width of span if the element is not visible

### LINKED ISSUE #44: Wrong position/width of span if the element is not visible
I have two forms one is hidden (display:none) and only shows when you submit the first form (ajax).

I tried making something like this:

$(form).fadeIn(200, function(){
    $('.custom-select').trigger('update');
});

But doesn't update the width and the position of the select box.

I'll try to see what's going on.

BTW thanks for the plugin!

### PR DESCRIPTION
**Pull request by markuspoerschke**
Fix #44 (https://github.com/adamcoulombe/jquery.customSelect/issues/44)

### CODE REVIEW

**Comment by markuspoerschke** [comment]
There is a little tweak: The if the select box is not visible it has to be located in an element wich is a) relative or b) absolute. It can be that if the position is different when a parent element is visible than the positioning could be wrong. This has to be done in CSS.

e.g.

``` HTML
<div class="hidden">
    <select> ... </select>
</div>
```

become

``` HTML
<div class="hidden">
    <div style="position: relative">
        <select> ... </select>
    </div>
</div>
```

**Comment by joshlopes** [comment]
That solution does not work. Have tested and nothing.

As work around i added this to source script:
if($select.is(':visible'))
    $select.css({
        '-webkit-appearance': 'menulist-button',
        width:                customSelectSpan.outerWidth(),
        position:             'absolute',
        opacity:              0,
        height:               selectBoxHeight,
        fontSize:             customSelectSpan.css('font-size')
        //left:                 position.left,
        //top:                  position.top
          });
else
    $select.css({
        '-webkit-appearance': 'menulist-button',
        width:                customSelectSpan.outerWidth(),
        position:             'absolute',
        opacity:              0,
        height:               selectBoxHeight \* 2,
        fontSize:             customSelectSpan.css('font-size')
        //left:                 position.left,
        //top:                  position.top
});

Ofc code isnt cleaned up all you have to do is alter the css that has diff after the default settings... good luck ;)

**Comment by adamcoulombe** [comment]
Folks, there are some different ways to get this working. The tested and true way is to just call customSelect after un-hiding, you should have no problems there.

If for some reason this is too inconvenient or not possible to do, you could also find which parent is causing your element to be hidden, then unhide it, then run customSelect, then re-hide it.

Example:
http://jsfiddle.net/adamco/pWacu/

This is something that could potentially be worked into the plugin, though at the moment I don't see this as a major priority that I will personally be implementing. My biggest issue is that it would be sacrificing file size and performance for a minor feature that I'm not sure everyone would need.

Of course if someone else is willing and able to add this type of solution I would be willing to consider merging it.

**Comment by adamcoulombe** [comment]
@eluceo I just looked at the commit and noticed that your code attempts to do something similar. It looks like quite a lot of code to add on for a relatively minor problem. I also haven't tested what you posted, but @joshlopes claims that it is not working. I'm wondering if it might just be better to add my example posted above to the cookbook in the documentation so people can do this themselves if needed, rather than add extra code to the actual plugin

**Comment by markuspoerschke** [comment]
@adamcoulombe The workaround looks good. I think this is a good solution. Adding the example to the cookbook would be nice!!

**Pull request closed without merging**
